// export const BASE_URL = 'http://localhost:8080/'
export const BASE_URL = 'http://api.tdocman.id.vn/api/'
export const BASE_URL_FE = 'http://tdocman.id.vn/'
export const BASE_ADMIN_URL = 'http://localhost:8081/'
export const BASE_PROVINCE_URL = 'https://vapi.vnappmob.com'
export const INTERNAL_SERVER_ERROR = 500
export const NOT_FOUND = 404
export const UNAUTHORIZED = 401
export const BAD_REQUEST = 400
export const FORBIDDEN = 403
export const GATEWAY_TIME_OUT = 504
export const REQUEST_SUCCESS = 200
export const months = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
